#IO引脚约束
create_clock -period 37.037 -name sys_clk [get_ports sys_clk]

# OV5640 720p 典型值为 84~96MHz，这里保守约束为 100MHz (10.000ns) 确保时序绝对安全
create_clock -period 10.000 -name camera_clk_0 [get_ports camera_clk_0]
create_clock -period 10.000 -name camera_clk_1 [get_ports camera_clk_1]
create_clock -period 10.000 -name camera_clk_2 [get_ports camera_clk_2]

# 以太网 RGMII 接收时钟 (RXC)
# 千兆以太网 RGMII 接收时钟标准频率为 125MHz (8.000ns)
create_clock -period 8.000 -name rgmii_clk [get_ports rgmii_rxc]

# 外部 HDMI 输入时钟 - 720p@60fps 标准 74.25MHz (13.468ns)
create_clock -period 13.468 -name pixclk_in [get_ports pixclk_in]

# 给以太网的 IDELAYCTRL 命名分组
set_property IODELAY_GROUP ETH_DELAY_GRP [get_cells IDELAYCTRL_inst]
# 给以太网 RGMII RX 底层模块分组
set_property IODELAY_GROUP ETH_DELAY_GRP [get_cells -hierarchical -filter {PRIMITIVE_TYPE =~ *IDELAY* && NAME =~ *ethernet_top_inst*}]

# 异步外设时钟
set_clock_groups -asynchronous -group [get_clocks sys_clk] -group [get_clocks clk_pll_i] -group [get_clocks clk_out1_ddr_clk] -group [get_clocks clk_out1_hdmi_clk] -group [get_clocks clk_out2_hdmi_clk] -group [get_clocks camera_clk_0] -group [get_clocks camera_clk_1] -group [get_clocks camera_clk_2] -group [get_clocks rgmii_clk] -group [get_clocks pixclk_in]

#----------------------系统时钟---------------------------
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports sys_clk]
#----------------------系统复位---------------------------
# set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]
#----------------------LED---------------------------
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports init_calib_complete]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports init_over]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD LVCMOS33} [get_ports led]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports cam_led0]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports cam_led1]
#----------------------IIC引脚约束---------------------------
# set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33} [get_ports hdmi_scl]
# set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS33} [get_ports hdmi_sda]

set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports hdmi_scl]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports hdmi_sda]

#----------------------UART引脚约束---------------------------
set_property -dict {PACKAGE_PIN B24 IOSTANDARD LVCMOS33} [get_ports uart_rx]
set_property -dict {PACKAGE_PIN C24 IOSTANDARD LVCMOS33} [get_ports uart_tx]

#----------------------HDMI TMDS引脚约束---------------------------
set_property -dict {PACKAGE_PIN N21 IOSTANDARD TMDS_33} [get_ports tmds_clk_p]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD TMDS_33} [get_ports tmds_clk_n]
set_property -dict {PACKAGE_PIN R25 IOSTANDARD TMDS_33} [get_ports {tmds_data_p[0]}]
set_property -dict {PACKAGE_PIN P25 IOSTANDARD TMDS_33} [get_ports {tmds_data_n[0]}]
set_property -dict {PACKAGE_PIN P23 IOSTANDARD TMDS_33} [get_ports {tmds_data_p[1]}]
set_property -dict {PACKAGE_PIN P24 IOSTANDARD TMDS_33} [get_ports {tmds_data_n[1]}]
set_property -dict {PACKAGE_PIN N23 IOSTANDARD TMDS_33} [get_ports {tmds_data_p[2]}]
set_property -dict {PACKAGE_PIN N24 IOSTANDARD TMDS_33} [get_ports {tmds_data_n[2]}]

#----------------------HDMI MS7200接口---------------------------
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports pixclk_in]
set_property -dict {PACKAGE_PIN G25 IOSTANDARD LVCMOS33} [get_ports rstn_out]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports vs_in]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports hs_in]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports de_in]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {r_in[0]}]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS33} [get_ports {r_in[1]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {r_in[2]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {r_in[3]}]
set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS33} [get_ports {r_in[4]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports {r_in[5]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {r_in[6]}]
set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports {r_in[7]}]
set_property -dict {PACKAGE_PIN J24 IOSTANDARD LVCMOS33} [get_ports {g_in[0]}]
set_property -dict {PACKAGE_PIN K23 IOSTANDARD LVCMOS33} [get_ports {g_in[1]}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33} [get_ports {g_in[2]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports {g_in[3]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {g_in[4]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports {g_in[5]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {g_in[6]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {g_in[7]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {b_in[0]}]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {b_in[1]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {b_in[2]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {b_in[3]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {b_in[4]}]
set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVCMOS33} [get_ports {b_in[5]}]
set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS33} [get_ports {b_in[6]}]
set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVCMOS33} [get_ports {b_in[7]}]

#----------------------HDMI引脚约束---------------------------
# set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVCMOS33} [get_ports pixclk_out]
# set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33} [get_ports vs_out]
# set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS33} [get_ports hs_out]
# set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports de_out]
# set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS33} [get_ports {r_out[0]}]
# set_property -dict {PACKAGE_PIN L23 IOSTANDARD LVCMOS33} [get_ports {r_out[1]}]
# set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS33} [get_ports {r_out[2]}]
# set_property -dict {PACKAGE_PIN L25 IOSTANDARD LVCMOS33} [get_ports {r_out[3]}]
# set_property -dict {PACKAGE_PIN L24 IOSTANDARD LVCMOS33} [get_ports {r_out[4]}]
# set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS33} [get_ports {r_out[5]}]
# set_property -dict {PACKAGE_PIN K25 IOSTANDARD LVCMOS33} [get_ports {r_out[6]}]
# set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {r_out[7]}]
# set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33} [get_ports {g_out[0]}]
# set_property -dict {PACKAGE_PIN P25 IOSTANDARD LVCMOS33} [get_ports {g_out[1]}]
# set_property -dict {PACKAGE_PIN R25 IOSTANDARD LVCMOS33} [get_ports {g_out[2]}]
# set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVCMOS33} [get_ports {g_out[3]}]
# set_property -dict {PACKAGE_PIN P23 IOSTANDARD LVCMOS33} [get_ports {g_out[4]}]
# set_property -dict {PACKAGE_PIN N24 IOSTANDARD LVCMOS33} [get_ports {g_out[5]}]
# set_property -dict {PACKAGE_PIN N23 IOSTANDARD LVCMOS33} [get_ports {g_out[6]}]
# set_property -dict {PACKAGE_PIN N22 IOSTANDARD LVCMOS33} [get_ports {g_out[7]}]
# set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports {b_out[0]}]
# set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS33} [get_ports {b_out[1]}]
# set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports {b_out[2]}]
# set_property -dict {PACKAGE_PIN M22 IOSTANDARD LVCMOS33} [get_ports {b_out[3]}]
# set_property -dict {PACKAGE_PIN M21 IOSTANDARD LVCMOS33} [get_ports {b_out[4]}]
# set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports {b_out[5]}]
# set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS33} [get_ports {b_out[6]}]
# set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports {b_out[7]}]

# set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports pixclk_in]
# set_property -dict {PACKAGE_PIN H24 IOSTANDARD LVCMOS33} [get_ports vs_in]
# set_property -dict {PACKAGE_PIN J23 IOSTANDARD LVCMOS33} [get_ports hs_in]
# set_property -dict {PACKAGE_PIN H23 IOSTANDARD LVCMOS33} [get_ports de_in]
# set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {r_in[0]}]
# set_property -dict {PACKAGE_PIN H19 IOSTANDARD LVCMOS33} [get_ports {r_in[1]}]
# set_property -dict {PACKAGE_PIN J19 IOSTANDARD LVCMOS33} [get_ports {r_in[2]}]
# set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports {r_in[3]}]
# set_property -dict {PACKAGE_PIN K20 IOSTANDARD LVCMOS33} [get_ports {r_in[4]}]
# set_property -dict {PACKAGE_PIN G21 IOSTANDARD LVCMOS33} [get_ports {r_in[5]}]
# set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {r_in[6]}]
# set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVCMOS33} [get_ports {r_in[7]}]
# set_property -dict {PACKAGE_PIN L14 IOSTANDARD LVCMOS33} [get_ports {g_in[0]}]
# set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {g_in[1]}]
# set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {g_in[2]}]
# set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports {g_in[3]}]
# set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {g_in[4]}]
# set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports {g_in[5]}]
# set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {g_in[6]}]
# set_property -dict {PACKAGE_PIN L15 IOSTANDARD LVCMOS33} [get_ports {g_in[7]}]
# set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {b_in[0]}]
# set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {b_in[1]}]
# set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {b_in[2]}]
# set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {b_in[3]}]
# set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports {b_in[4]}]
# set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports {b_in[5]}]
# set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports {b_in[6]}]
# set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {b_in[7]}]
#----------------------ov5640_0---------------------------
# set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports camera_clk_2]
# set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[0]}]
# set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[1]}]
# set_property -dict {PACKAGE_PIN Y26 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[2]}]
# set_property -dict {PACKAGE_PIN W25 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[3]}]
# set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[4]}]
# set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[5]}]
# set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[6]}]
# set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[7]}]
# set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports camera_href_2]
# set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVCMOS33} [get_ports camera_vsync_2]
# set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports SCL_2]
# set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports SDA_2]
# set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports cam_rst_2]

set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVCMOS33} [get_ports camera_clk_0]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {camera_data_0[0]}]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports {camera_data_0[1]}]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVCMOS33} [get_ports {camera_data_0[2]}]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS33} [get_ports {camera_data_0[3]}]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {camera_data_0[4]}]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {camera_data_0[5]}]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports {camera_data_0[6]}]
set_property -dict {PACKAGE_PIN V14 IOSTANDARD LVCMOS33} [get_ports {camera_data_0[7]}]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports camera_href_0]
set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVCMOS33} [get_ports camera_vsync_0]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports SCL_0]
set_property -dict {PACKAGE_PIN U14 IOSTANDARD LVCMOS33} [get_ports SDA_0]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports cam_rst_0]

set_property -dict {PACKAGE_PIN L22 IOSTANDARD LVCMOS33} [get_ports camera_clk_2]
set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[0]}]
set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[1]}]
set_property -dict {PACKAGE_PIN K26 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[2]}]
set_property -dict {PACKAGE_PIN K25 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[3]}]
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[4]}]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[5]}]
set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[6]}]
set_property -dict {PACKAGE_PIN R21 IOSTANDARD LVCMOS33} [get_ports {camera_data_2[7]}]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33} [get_ports camera_href_2]
set_property -dict {PACKAGE_PIN L23 IOSTANDARD LVCMOS33} [get_ports camera_vsync_2]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports SCL_2]
set_property -dict {PACKAGE_PIN R20 IOSTANDARD LVCMOS33} [get_ports SDA_2]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports cam_rst_2]
#----------------------ov5640_1---------------------------
#set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports camera_clk_1]
#set_property -dict {PACKAGE_PIN V21 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[0]}]
#set_property -dict {PACKAGE_PIN U26 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[1]}]
#set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[2]}]
#set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[3]}]
#set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[4]}]
#set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[5]}]
#set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[6]}]
#set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[7]}]
#set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports camera_href_1]
#set_property -dict {PACKAGE_PIN V23 IOSTANDARD LVCMOS33} [get_ports camera_vsync_1]
#set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports SCL_1]
#set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports SDA_1]
#set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS33} [get_ports cam_rst_1]

set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS33} [get_ports camera_clk_1]
set_property -dict {PACKAGE_PIN V21 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[0]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[1]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[2]}]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[3]}]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[4]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[5]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[6]}]
set_property -dict {PACKAGE_PIN Y20 IOSTANDARD LVCMOS33} [get_ports {camera_data_1[7]}]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS33} [get_ports camera_href_1]
set_property -dict {PACKAGE_PIN V24 IOSTANDARD LVCMOS33} [get_ports camera_vsync_1]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports SCL_1]
set_property -dict {PACKAGE_PIN V23 IOSTANDARD LVCMOS33} [get_ports SDA_1]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS33} [get_ports cam_rst_1]
#----------------------video_sel---------------------------
set_property -dict {PACKAGE_PIN C22 IOSTANDARD LVCMOS33} [get_ports {key[0]}]
set_property -dict {PACKAGE_PIN C23 IOSTANDARD LVCMOS33} [get_ports {key[1]}]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD LVCMOS33} [get_ports {key[2]}]
set_property -dict {PACKAGE_PIN A22 IOSTANDARD LVCMOS33} [get_ports {key[3]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {key[4]}]

#----------------------ethernet---------------------------
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports rgmii_rxc]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports rgmii_rx_ctl]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports {rgmii_rxd[3]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD LVCMOS33} [get_ports {rgmii_rxd[2]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {rgmii_rxd[1]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD LVCMOS33} [get_ports {rgmii_rxd[0]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports rgmii_txc]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports rgmii_tx_ctl]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD LVCMOS33} [get_ports {rgmii_txd[3]}]
set_property -dict {PACKAGE_PIN C21 IOSTANDARD LVCMOS33} [get_ports {rgmii_txd[2]}]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD LVCMOS33} [get_ports {rgmii_txd[1]}]
set_property -dict {PACKAGE_PIN E20 IOSTANDARD LVCMOS33} [get_ports {rgmii_txd[0]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]